pipeline {

    agent any


    stages {


        stage('Checkout Code') {

            steps {

                git branch: 'main',
                credentialsId: 'freebird2318-coder',
                url: 'https://github.com/freebird2318-coder/freshshop-master-CICD-jenkins-sonarqube-docker.git'

            }
        }



        stage('Deploy To Docker Server') {

            steps {


                sshagent(['docker-creds']) {


                    sh '''

                    ssh -o StrictHostKeyChecking=no ubuntu@54.145.217.16 "
                    mkdir -p ~/website
                    "


                    scp -o StrictHostKeyChecking=no -r \
                    freshshop-master \
                    ubuntu@54.145.217.16:~/website/


                    ssh -o StrictHostKeyChecking=no ubuntu@54.145.217.16 "

                    cd ~/website/freshshop-master


                    docker rm -f freshshop-master || true


                    docker build -t mywebsite1 .


                    docker run -d \
                    -p 8086:80 \
                    --name freshshop-master1 \
                    mywebsite


                    "


                    ssh -o StrictHostKeyChecking=no ubuntu@54.145.217.16 "

                    docker ps

                    "


                    '''

                }

            }

        }


    }

}

